### PR TITLE
Fixed incorrect function name in page/tournament_creation

### LINKED ISSUE #82: Visiting /tournament_creation crashes server
Changes to `src/player_dropdown` broke `page/tournament_creation.js`

### PR DESCRIPTION
**Pull request by AlgorithmicEntropy**
Fixed issues in db/user_in_group
Replaced hardcoded group members with correct ones from db

Closes #82

### CODE REVIEW

File: src/db/user_in_group.js [hunk 1]
```diff
@@ -5,7 +5,7 @@ const database = require('../database')
 
 const UserInGroup = class {
   constructor (userInGroup) {
-    this._id = userInGroup.id
+    this._id = userInGroup.group_id
```
Comment (DavidRisch) [inline src/db/user_in_group.js]: `group_id`(alone) is not a PK. This file has (and has allways had) sigificant problems. I suggest deleting it. Only the the `add_User` function is ever used (never the class), this should be moved to `db/group`.

File: page/tournament_creation.js [hunk 2]
```diff
@@ -1,8 +1,24 @@
 function page (req, res) {
+  // get user and group
+  const user = require('../src/account_util').get_current_user(req)
+  if (!user) {
```
Comment (DavidRisch) [inline page/tournament_creation.js]: Why not use `require_logged_in_user`?

File: page/tournament_creation.js [hunk 3]
```diff
@@ -1,8 +1,24 @@
...
+    // not auth --> redirect to auth
+    res.cookie('redirect', req.url)
+    res.writeHead(302, { Location: '/login' })
+    res.end()
+    return
+  }
+
+  // get group from cookie
+  const groupID = require('../src/account_util').get_group(req)
```
Comment (DavidRisch) [inline page/tournament_creation.js]: Variable not camelCase

**Review by DavidRisch — CHANGES_REQUESTED** [review]
